import type {
  AchievementDef,
  BuildingDef,
  ExchangeRate,
  GameConfig,
  PlayerState,
  ResourceId,
  ResourceDef,
  TechDef,
} from './types';

export const RESOURCES: ResourceDef[] = [
  { id: 'money', name: 'Credits', icon: 'coin' },
  { id: 'energy', name: 'Energy', icon: 'bolt' },
  { id: 'research', name: 'Research', icon: 'flask' },
];

export const BUILDINGS: BuildingDef[] = [
  {
    id: 'collector',
    name: 'Solar Collector',
    short: 'COL',
    icon: 'solar',
    plot: 'A',
    description: 'Converts irradiance into grid energy.',
    costBase: 10,
    costGrowth: 1.15,
    baseRate: 1,
    perLevelRate: 1.1,
    output: 'energy',
  },
  {
    id: 'refinery',
    name: 'Refinery',
    short: 'REF',
    icon: 'refinery',
    plot: 'B',
    description: 'Refines energy into export credits.',
    costBase: 30,
    costGrowth: 1.18,
    baseRate: 1.2,
    perLevelRate: 1.8,
    output: 'money',
    input: { resource: 'energy', perLevel: 0.6 },
  },
  {
    id: 'wind_turbine',
    name: 'Wind Turbine',
    short: 'TUR',
    icon: 'wind',
    plot: 'C',
    description: 'Reinforces the power supply with wind.',
    costBase: 80,
    costGrowth: 1.2,
    baseRate: 1.6,
    perLevelRate: 1.5,
    output: 'energy',
  },
  {
    id: 'lab',
    name: 'Laboratory',
    short: 'LAB',
    icon: 'lab',
    plot: 'D',
    description: 'Consumes energy to produce research.',
    costBase: 200,
    costGrowth: 1.22,
    baseRate: 0.5,
    perLevelRate: 0.5,
    output: 'research',
    input: { resource: 'energy', perLevel: 1 },
  },
];

export const TECHS: TechDef[] = [
  {
    id: 'solar_v1',
    name: 'Cell Reinforcement',
    description: 'Solar collector: output x2.',
    tree: 'Energy',
    tileX: 0,
    tileY: 0,
    requires: [],
    cost: { resource: 'money', amount: 30 },
    effects: [{ t: 'multiply_building_output', building: 'collector', multiplier: 2 }],
  },
  {
    id: 'solar_v2',
    name: 'Tandem Cells',
    description: 'Solar collector: output x2.',
    tree: 'Energy',
    tileX: 0,
    tileY: 1,
    requires: ['solar_v1'],
    cost: { resource: 'money', amount: 120 },
    effects: [{ t: 'multiply_building_output', building: 'collector', multiplier: 2 }],
  },
  {
    id: 'turbines',
    name: 'Wind Farm',
    description: 'Unlocks the wind turbine.',
    tree: 'Energy',
    tileX: 0,
    tileY: 2,
    requires: ['solar_v2'],
    cost: { resource: 'money', amount: 400 },
    effects: [{ t: 'unlock_building', building: 'wind_turbine' }],
  },
  {
    id: 'solar_v3',
    name: 'Photonics',
    description: 'Solar and wind: output x2.',
    tree: 'Energy',
    tileX: 0,
    tileY: 3,
    requires: ['solar_v2', 'lab_blueprint'],
    cost: { resource: 'research', amount: 40 },
    effects: [
      { t: 'multiply_building_output', building: 'collector', multiplier: 2 },
      { t: 'multiply_building_output', building: 'wind_turbine', multiplier: 2 },
    ],
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    description: 'Unlocks the refinery.',
    tree: 'Production',
    tileX: 1,
    tileY: 0,
    requires: [],
    cost: { resource: 'money', amount: 50 },
    effects: [{ t: 'unlock_building', building: 'refinery' }],
  },
  {
    id: 'automation',
    name: 'Automation',
    description: 'Refinery: output x2.',
    tree: 'Production',
    tileX: 1,
    tileY: 1,
    requires: ['metallurgy'],
    cost: { resource: 'money', amount: 300 },
    effects: [{ t: 'multiply_building_output', building: 'refinery', multiplier: 2 }],
  },
  {
    id: 'logistics',
    name: 'Logistics',
    description: 'Refinery x2 and collector x1.5.',
    tree: 'Production',
    tileX: 1,
    tileY: 2.5,
    requires: ['automation', 'lab_blueprint'],
    cost: { resource: 'research', amount: 25 },
    effects: [
      { t: 'multiply_building_output', building: 'refinery', multiplier: 2 },
      { t: 'multiply_building_output', building: 'collector', multiplier: 1.5 },
    ],
  },
  {
    id: 'lab_blueprint',
    name: 'Laboratory Blueprint',
    description: 'Unlocks the laboratory.',
    tree: 'Expansion',
    tileX: 2,
    tileY: 1.5,
    requires: ['solar_v2', 'metallurgy'],
    cost: { resource: 'money', amount: 600 },
    effects: [{ t: 'unlock_building', building: 'lab' }],
  },
  {
    id: 'grid_boost',
    name: 'Trunk Grid',
    description: 'All site output x1.5.',
    tree: 'Expansion',
    tileX: 2,
    tileY: 3,
    requires: ['solar_v3', 'logistics'],
    cost: { resource: 'research', amount: 60 },
    effects: [{ t: 'add_global_output', multiplier: 1.5 }],
  },
  {
    id: 'quantum_core',
    name: 'Quantum Core',
    description: 'Global output x2 and more offline time.',
    tree: 'Expansion',
    tileX: 3,
    tileY: 4,
    requires: ['grid_boost'],
    cost: { resource: 'research', amount: 150 },
    effects: [
      { t: 'add_global_output', multiplier: 2 },
      { t: 'offline_cap', multiplier: 2 },
    ],
  },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_light',
    name: 'First Light',
    description: 'Produce 100 energy in total.',
    condition: { type: 'resource_total', resource: 'energy', amount: 100 },
    reward: { t: 'building_output', building: 'collector', multiplier: 1.05 },
    visible: true,
  },
  {
    id: 'power_grid',
    name: 'Power Grid',
    description: 'Produce 10,000 energy in total.',
    condition: { type: 'resource_total', resource: 'energy', amount: 10_000 },
    reward: { t: 'building_output', building: 'collector', multiplier: 1.1 },
    visible: true,
  },
  {
    id: 'energy_baron',
    name: 'Energy Baron',
    description: 'Produce 1,000,000 energy in total.',
    condition: { type: 'resource_total', resource: 'energy', amount: 1_000_000 },
    reward: { t: 'building_output', building: 'collector', multiplier: 1.15 },
    visible: true,
  },
  {
    id: 'credit_rush',
    name: 'Credit Rush',
    description: 'Earn 1,000 credits in total.',
    condition: { type: 'resource_total', resource: 'money', amount: 1_000 },
    reward: { t: 'building_output', building: 'refinery', multiplier: 1.05 },
    visible: true,
  },
  {
    id: 'tycoon',
    name: 'Tycoon',
    description: 'Earn 100,000 credits in total.',
    condition: { type: 'resource_total', resource: 'money', amount: 100_000 },
    reward: { t: 'building_output', building: 'refinery', multiplier: 1.1 },
    visible: true,
  },
  {
    id: 'research_pioneer',
    name: 'Research Pioneer',
    description: 'Produce 100 research in total.',
    condition: { type: 'resource_total', resource: 'research', amount: 100 },
    reward: { t: 'building_output', building: 'lab', multiplier: 1.05 },
    visible: true,
  },
  {
    id: 'scientist',
    name: 'Scientist',
    description: 'Produce 10,000 research in total.',
    condition: { type: 'resource_total', resource: 'research', amount: 10_000 },
    reward: { t: 'building_output', building: 'lab', multiplier: 1.1 },
    visible: true,
  },
  {
    id: 'site_manager',
    name: 'Site Manager',
    description: 'Own 5 buildings.',
    condition: { type: 'building_count', amount: 5 },
    reward: { t: 'building_cost', multiplier: 0.95 },
    visible: true,
  },
  {
    id: 'foreman',
    name: 'Foreman',
    description: 'Own 20 buildings.',
    condition: { type: 'building_count', amount: 20 },
    reward: { t: 'building_cost', multiplier: 0.92 },
    visible: true,
  },
  {
    id: 'mogul',
    name: 'Mogul',
    description: 'Own 50 buildings.',
    condition: { type: 'building_count', amount: 50 },
    reward: { t: 'building_cost', multiplier: 0.88 },
    visible: true,
  },
  {
    id: 'tech_enthusiast',
    name: 'Tech Enthusiast',
    description: 'Unlock 5 technologies.',
    condition: { type: 'tech_count', amount: 5 },
    reward: { t: 'tech_cost', multiplier: 0.95 },
    visible: true,
  },
  {
    id: 'market_merchant',
    name: 'Market Merchant',
    description: 'Complete 50 trades.',
    condition: { type: 'trades_done', amount: 50 },
    reward: { t: 'trade_rate', multiplier: 1.08 },
    visible: true,
  },
  {
    id: 'collector_expert',
    name: '???',
    description: '???',
    condition: { type: 'building_level', building: 'collector', amount: 10 },
    reward: { t: 'building_output', building: 'collector', multiplier: 1.1 },
    visible: false,
  },
  {
    id: 'refinery_master',
    name: '???',
    description: '???',
    condition: { type: 'building_level', building: 'refinery', amount: 10 },
    reward: { t: 'building_output', building: 'refinery', multiplier: 1.1 },
    visible: false,
  },
  {
    id: 'innovator',
    name: '???',
    description: '???',
    condition: { type: 'all_techs' },
    reward: { t: 'global_output', multiplier: 1.05 },
    visible: false,
  },
];

export const EXCHANGE: ExchangeRate[] = [
  { id: 'sell_energy', from: 'energy', to: 'money', factor: 0.25 },
  { id: 'buy_energy', from: 'money', to: 'energy', factor: 1.6 },
  { id: 'sell_research', from: 'research', to: 'money', factor: 0.25 },
  { id: 'buy_research', from: 'money', to: 'research', factor: 1.6 },
];

export const GAME_CONFIG: GameConfig = {
  version: 1,
  resources: RESOURCES,
  buildings: BUILDINGS,
  techs: TECHS,
  achievements: ACHIEVEMENTS,
  exchange: EXCHANGE,
  offline: { maxHours: 48, efficiency: 1 },
};

export function newPlayer(): PlayerState {
  const resources: Record<string, number> = {};
  for (const r of RESOURCES) resources[r.id] = 0;
  return {
    version: GAME_CONFIG.version,
    resources: { ...resources, money: 60 },
    buildings: { collector: 1 },
    unlocked: { collector: true },
    techs: {},
    stats: { earned: { ...resources }, totalTrades: 0 },
    achievements: {},
    achievementClaimed: {},
  };
}

export function resourceDef(config: GameConfig, id: ResourceId): ResourceDef {
  const def = config.resources.find((r) => r.id === id);
  if (!def) throw new Error(`unknown resource: ${id}`);
  return def;
}